export { default as CrudView } from "./CrudView";
export { default as DesktopDashboardView } from "./DesktopDashboardView";
export { default as KpiCard } from "./KpiCard";
export { default as MobileAppSimulator } from "./MobileAppSimulator";
export { default as RoutesView } from "./RoutesView";
export { default as SapIntegrationView } from "./SapIntegrationView";
export { default as SidebarItem } from "./SidebarItem";
export { default as VoicePickingView } from "./VoicePickingView";
export { default as WhatsAppAgentView } from "./WhatsAppAgentView";
